spring.application.name=App16-JPA

spring.datasource.url=jdbc:postgresql://localhost:5432/JPA-practice
spring.datasource.username=postgres
spring.datasource.password=postgres


# JPA / Hibernate
# It ensures Hibernate generates SQL that is compatible with PostgreSQL syntax and features
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# lets Hibernate auto-create/update tables
spring.jpa.hibernate.ddl-auto=update

# logs SQL being run
spring.jpa.show-sql=true
